# This rule is not used by the project notifik itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over notifik.freepik.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: notifik
    app.kubernetes.io/managed-by: kustomize
  name: integration-admin-role
rules:
- apiGroups:
  - notifik.freepik.com
  resources:
  - integrations
  verbs:
  - '*'
- apiGroups:
  - notifik.freepik.com
  resources:
  - integrations/status
  verbs:
  - get
