# This rule is not used by the project notifik itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to notifik.freepik.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: notifik
    app.kubernetes.io/managed-by: kustomize
  name: integration-viewer-role
rules:
- apiGroups:
  - notifik.freepik.com
  resources:
  - integrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notifik.freepik.com
  resources:
  - integrations/status
  verbs:
  - get
