apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "notifik.fullname" . }}-manager
  labels:
    {{- include "notifik.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - notifik.freepik.com
    resources:
    - integrations
    - notifications
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - notifik.freepik.com
    resources:
    - integrations/finalizers
    - notifications/finalizers
    verbs:
    - update
  - apiGroups:
    - notifik.freepik.com
    resources:
    - integrations/status
    - notifications/status
    verbs:
    - get
    - patch
    - update

