apiVersion: notifik.freepik.com/v1alpha1
kind: Notification
metadata:
  name: notification-sample-simple
spec:
  # Resource to be watched
  watch:
    group: ""
    version: v1
    resource: configmaps

    # (Optional) It's possible to watch specific resources
    # name: testing
    # namespace: default


  conditions:
    - name: check-configmap-name
      # The 'key' field admits vitamin Golang templating (well known from Helm)
      # The result of this field will be compared with 'value' for equality
      key: |
        {{- $object := .object -}}
        {{- printf "%s" $object.metadata.name -}}
      value: testing

  message:
    integration:
      name: webhook-sender
    data: |
      {{- $object := .object -}}
      {{- printf "Hi, I'm on fire with the alert 'NameMatchedAlert': %s/%s" $object.metadata.namespace $object.metadata.name -}}
